### ISSUE TITLE
Support for DECIMAL data type 

### ISSUE THREAD

**Issue by vecchiocarmelo** [prestodb/RPresto#60]
If  I try to query on a decimal column I get the error: 

```
Error in .json.tabular.to.data.frame(data.list, r.types, timezone = timezone) : 
Unsupported column type: NA

```
Decimal is a supported data type for Presto:

https://prestodb.io/docs/current/language/types.html

If i cast the column as DOUBLE i can read the data.

**Comment by cosinequanon** [comment]
Thanks for reporting! This is a pretty new data type so we haven't had time to add it yet, we are also very happy to review pull requests :)

**Comment by onurfiliz** [comment]
Should be fixed by #59 .

**Comment by vecchiocarmelo** [comment]
It seems that the issue is not resolved, simply the error message is changed:

`Error: unrecognized string value in numeric vector!`

If i cast the column as DOUBLE i can read the data.

**Comment by cosinequanon** [comment]
This is happening because of the Rcpp stuff we added, Presto is returning a string in the JSON response but Rcpp things we have a numeric type. Not sure what the best solution is just yet.
